# Generated by Django 5.0.3 on 2024-03-06 01:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúñ\\s]*$', 'El/Los nombre(s) no puede poseer caracteres extraños')])),
                ('apellidos', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúñ\\s]*$', 'El/Los apellido(s) no puede poseer caracteres extraños')])),
                ('direccion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DpLegal',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('funciones', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Departamento Legal',
                'verbose_name_plural': 'Departamentos Legales',
                'db_table': 'dp_legal',
            },
        ),
        migrations.CreateModel(
            name='DpComercial',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('funciones', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('dp_legal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dp_comercial', to='main.dplegal')),
            ],
            options={
                'verbose_name': 'Departamento Comercial',
                'verbose_name_plural': 'Departamentos Comerciales',
                'db_table': 'dp_comercial',
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('trabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nivelEscolar', models.CharField(choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('BACH', 'Bachillerato'), ('UNIV', 'Universidad')], max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='main.dpcomercial')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.trabajador',),
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('trabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comerciales', to='main.dpcomercial')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.trabajador',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('trabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gradoAcademico', models.CharField(choices=[('TEC', 'Tecnico'), ('ING', 'Ingeniero'), ('LIC', 'Licenciado'), ('MAE', 'Maestria'), ('DOC', 'Doctorado')], max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directores', to='main.dpcomercial')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.trabajador',),
        ),
    ]
