# Generated by Django 5.0.3 on 2024-03-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='asistente',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='director',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
