# Generated by Django 5.0.3 on 2024-03-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
