# Generated by Django 5.0.3 on 2024-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contrato_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='tipo',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
