# Generated by Django 5.0.3 on 2024-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trabajador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tipo',
            field=models.CharField(default='Admin', editable=False, max_length=255),
        ),
    ]
