# Generated by Django 5.0.3 on 2024-03-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_asistente_anioexperiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='fechaNacimiento',
            field=models.DateField(default='2002-01-21'),
        ),
    ]
