# Generated by Django 5.0.3 on 2024-03-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_asistente_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='periodo_validez',
            field=models.DateField(),
        ),
    ]
