# Generated by Django 5.0.3 on 2024-03-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_trabajador_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo',
        ),
    ]
