# Generated by Django 5.0.3 on 2024-03-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contrato_codigo_alter_informe_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_producion',
            new_name='fecha_produccion',
        ),
        migrations.AlterField(
            model_name='informe',
            name='codigo',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
