# Generated by Django 5.0.3 on 2024-03-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_fecha_producion_producto_fecha_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_compra',
            field=models.DateField(),
        ),
    ]
